### ISSUE TITLE
PGID is wrong

### ISSUE THREAD

**Issue by modem7** [dullage/flatnotes#100]
In the [documentation](https://github.com/dullage/flatnotes#example-docker-compose), it shows GUID as the group var, whereas it should be PGID:

https://github.com/dullage/flatnotes/blob/374e28e7607429938ff26290566d1032a4fd95a8/entrypoint.sh#L7-L22

**Comment by dullage** [comment]
Thanks for this! I've updated the README and also the wiki article on environment variables (as that was also wrong!). I'd also used `guid` in the exec command in `entrypoint.sh` so I fixed that as well!

**Comment by modem7** [comment]
Perfik! Cheers!

I would have raised a PR, but wasn't sure how deep the rabbithole went!
