### ISSUE TITLE
Real IP in logs

### ISSUE THREAD

**Issue by modem7** [dullage/flatnotes#101]
This is definitely more of a wishlist request.

Within the logs, I can see the IP addresses being logged, but they're all internal Docker addresses. 

Is there a way for the logs to see the X-Forwarded headers to get the real IP addresses that Traefik/the reverse proxy is giving?

**Comment by dullage** [comment]
It's uvicorn that's doing the logging so it would be a uvicorn config option that would need to be changed. The 2 links below may help:

- [https://www.uvicorn.org/settings/#http](https://www.uvicorn.org/settings/#http)
- [https://stackoverflow.com/questions/66109609/how-do-i-capture-x-forwarded-for-with-fastapi-logging](https://stackoverflow.com/questions/66109609/how-do-i-capture-x-forwarded-for-with-fastapi-logging)

It might be as simple as adding `--proxy-headers` and `--forwarded-allow-ips "*"` to the uvicorn command but I'm unsure whether there are any security considerations with this (or whether it would work).

**Comment by modem7** [comment]
So, I've done a couple of tests:

`--proxy-headers` only does not work
`--proxy-headers` & `--forwarded-allow-ips '*'` does work.

I've also found the below, unsure if it'd help:

https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/224#issuecomment-737423886

**Comment by dullage** [comment]
Given that flatnotes doesn't use the IP address for anything other than logging, I'm happy to trust all proxies here.

I've added these 2 options to the uvicorn command and the real IPs are now showing in the log. See [this commit](https://github.com/dullage/flatnotes/commit/b19062de8a580c7c6a309b1c142d0fb570039abb).

**Comment by holzerseb** [comment]
Thanks @dullage for Flatnotes. I'm still having this problem: in the logs only the internal docker ips are logged. Using nginx with X-Forward headers and the latest flatnotes version with the commit you mentioned - verified entrypoint.sh does use the uvicorn commands. But it's still reporting the docker IP. Besides x-forward and uvicorn header commands, am I missing something? If it helps, I could try the AGSI middleware approach.
Primarily want to put fail2ban in front.
