### ISSUE TITLE
File Name and Year Search

### ISSUE THREAD

**Issue by passionate2023** [dullage/flatnotes#103]
Need file name search and year search options

from year to to year

assume the file name is associated with a tag or a year tag for each note

**Comment by dullage** [comment]
Good news, this is already possible. Please see this [wiki article](https://github.com/dullage/flatnotes/wiki/Advanced-Searching) and also the [docs for Whoosh](https://whoosh.readthedocs.io/en/latest/querylang.html#fields) (the package used for search).
