### ISSUE TITLE
Open URL in new tab

### ISSUE THREAD

**Issue by rb-26** [dullage/flatnotes#106]
It would be awesome if there was an option to open clickable URLs in a new tab rather than the one you are working in.

**Comment by dullage** [comment]
I wouldn't want to change the default behaviour on this or add a config option either. But there are a couple of workarounds:

1. CTRL-Click the link. Probably obvious but just in case you're unaware of this shortcut.
2. Use an `a` tag with a target set e.g. <a href="https://example.com/" target="_blank">Example</a>`.
