### ISSUE TITLE
Browse without webserver

### ISSUE THREAD

**Issue by berot3** [dullage/flatnotes#108]
Hi 👋

Just wondering, is it possible to "print out" to static html and browse the html via file:/// url in the browser?

Similar to mkdocs https://github.com/mkdocs/mkdocs/issues/2189

Depending on the case, this has some good advantages.

**Comment by dullage** [comment]
I'm afraid not. Also, the markdown rendering is done on the client (browser) side which would likely make this tricky to implement.

Out of interest, what's the usefulness of this? Is it just to negate the need for the server?

**Comment by berot3** [comment]
@dullage 
> I'm afraid not. Also, the markdown rendering is done on the client (browser) side which would likely make this tricky to implement.

I see, thanks for checking!


> Out of interest, what's the usefulness of this? Is it just to negate the need for the server?

Correct, no need to spin up a web-server. Also you can sync the files with smb, iCloud or whatever and everyone would see the current htmls, without the need of network/firewall or VPN fiddling
