### ISSUE TITLE
add 'pin note' feature

### ISSUE THREAD

**Issue by pbogre** [dullage/flatnotes#109]
i would like to be able to have quick access to some notes, maybe even if i haven't edited them recently but they are something i need to keep going back to look at because of their information. 

with this feature, you could have the 'recently modified' section available unless you have any pinned notes, in which case that section is replaced with a 'pinned notes' section. 

there are also others way to approach the UI aspect of this, for example making the text that currently says 'recently modified' with a minimalist toggle menu that allows you to choose which notes to display. this allows for further ui customization like 'recently viewed', 'recently created', etc.

**Comment by dullage** [comment]
Hi @pbogre. Thanks for the suggestion. Unfortunately, without a database, there wouldn't really be a clean way to store which notes were pinned. The only thing I can suggest is bookmarking the URL for the notes you need quick access to.

**Comment by pbogre** [comment]
ah that makes sense. however i believe that through an improvement of the homepage ui (improvement for which has also been requested in other issues, like a grid view) could achieve something similar. 

for instance, if we had an option to filter the notes seen in the homepage with something like tags, you could put a "pinned" tag on notes and by filtering only notes with that tag it would be the same thing as assigning a pinned value to the note. this would also add functionality to the tag feature which in my experience hasn't been very useful very often.

the suggestion about different types of notes to show on the homepage still stands however, and what i wrote in this comment uses that change to implement a way to pin notes based on tags with a filter

**Comment by dullage** [comment]
The idea of using tags is a good one. I hadn't considered that.

**Comment by dullage** [comment]
I'm pleased to say that this is now possible using the new [Quick Access Notes feature added in v5.3.0](https://github.com/dullage/flatnotes/releases/tag/v5.3.0).
