### ISSUE TITLE
Allow saving without closing of the note

### ISSUE THREAD

**Issue by Mladia** [dullage/flatnotes#115]
Currently, after clicking "save note", the view changes back to the note overview. For a user to continue editing of the same note, clicking "edit" is needed to go back to editing view.

Allowing the option to _quick save_ the currently edited note without changing the view or closing of the note will help usability.
 
_Originally referenced by @dullage in https://github.com/dullage/flatnotes/issues/59#issuecomment-1692809816_

**Comment by dullage** [comment]
Thanks 👍. I'll have a think about this.

**Comment by bverkron** [comment]
+1 for this!

**Comment by jokob-sk** [comment]
+1

**Comment by dullage** [comment]
I've just merged a change into the develop branch that allows for notes to be saved without closing the note:

![image](https://github.com/dullage/flatnotes/assets/16575268/8b2da818-d63a-4bea-bc77-9af569d98169)

Additionally, I've added 2 new keyboard shortcuts available when editing a note:

`CTRL-Enter` - Save (without closing)
`Escape` - Close the note

If anyone wants to give this a go before release you can pull and run the `dullage/flatnotes:develop` image.

**Comment by dullage** [comment]
This change is now available in [5.2.0](https://github.com/dullage/flatnotes/releases/tag/v5.2.0). 🚀
