### ISSUE TITLE
Increase font size difference between header levels

### ISSUE THREAD

**Issue by pbogre** [dullage/flatnotes#117]
I feel like the difference in font size between headers it too small for it to be visually apparent. I often find myself having to increment the header level by 2 instead of just 1 because when scrolling through the note it's hard to differentiate between headers of similar level because they are so similar in size.

**Comment by dullage** [comment]
I would like to completely overhaul the typography in the editor but it's a fair bit of work to make it play nicely with the stylesheet that comes with it. I'll hopefully get to this at some point.

**Comment by dullage** [comment]
@pbogre - Please take a look at [v3.6.0](https://github.com/dullage/flatnotes/releases/tag/v3.6.0). Hopefully this resolves the suggestion (but may not as it's a subjective thing).

**Comment by pbogre** [comment]
had a look at the demo site and it is definitely a lot better now. Thank you very much for the new release :).

Closed by v3.6.0
