### ISSUE TITLE
Unable to run rootless docker due to entrypoint.sh forcing custom user, chown usage & gosu trying to switch user when already running on the right user.

### ISSUE THREAD

**Issue by kitsumed** [dullage/flatnotes#120]
In your current version (3.2.3) [entrypoint.sh ](https://github.com/dullage/flatnotes/blob/970a34ce371d909f81e34705f9cb7b93525f1bcd/entrypoint.sh) is forcing the creation of a new user, as well as the use of the chown command at every launch (which seem to be a bad practice according to your current usage of it as it force us to keep this docker capability enabled : https://www.redhat.com/en/blog/secure-your-containers-one-weird-trick). It also try to switch to the selected user mentioned in the environment values even if the user is already matching the said value.

Assuming docker capabilities are dropped :
This behaviors prevent from starting the docker as a custom user (rootless in this case) from the docker user argument. The same issue arise for PUID and PGID environment values. It should however be possible to run this script on a custom rootless user without any docker capabilities as the program in itself doesn't depend on them, I think entrypoint.sh is at fault here.

In the following examples, user 1001 is a rootless user.

From environment values:
```
Setting up user and group...
addgroup: The group `flatnotes' already exists.
Group '1001' already exists.
adduser: The user `flatnotes' already exists.
User '1001' already exists.
Setting file permissions...
chown: changing ownership of '/data/.flatnotes': Operation not permitted
chown: changing ownership of '/data': Operation not permitted
```
From docker user argument:
```
Setting up user and group...
addgroup: Only root may add a user or group to the system.
Group '1000' already exists.
adduser: Only root may add a user or group to the system.
User '1000' already exists.
Setting file permissions...
chown: changing ownership of '/data/.flatnotes': Operation not permitted
chown: changing ownership of '/data': Operation not permitted
```
From the docker user argument and the environment values: (Failed switching to 1001:1001 when already running on 1001:1001, why switching in the first place?)
```
Setting up user and group...
addgroup: Only root may add a user or group to the system.
Group '1001' already exists.
adduser: Only root may add a user or group to the system.
User '1001' already exists.
Setting file permissions...
WARNING: Breaking changes introduced in version 3.x:
  - The port flatnotes uses inside the Docker container has been changed to 8080 (previously 80).
  - To accompany the above change, support for the PORT environment variable has been removed.
  - The note directory inside the Docker container has moved from /app/data to simply /data.
Starting flatnotes...
error: failed switching to "1001:1001": operation not permitted
```

Also note that I am binding the whole /data folder with write access. All file and folders are allowing 1001:1001 to write, read and create files.

**Comment by dullage** [comment]
Thank you for the information. Is your proposal to simply skip the user creation and ownership changes if the entrypoint script finds itself running as a non-root user?

This would then rely on the admin to manually ensure that ownership of the mapped volume and files matches the user they are using to run the container. Essentially ignoring the PUID and PGID environment variables.

**Comment by kitsumed** [comment]
> Thank you for the information. Is your proposal to simply skip the user creation and ownership changes if the entrypoint script finds itself running as a non-root user?
> 
> This would then rely on the admin to manually ensure that ownership of the mapped volume and files matches the user they are using to run the container. Essentially ignoring the PUID and PGID environment variables.

Yes, that would be a way to prevent the issue. You could print a message in the console telling the user it detected it was running as a non-root and skipped these steps.
