### ISSUE TITLE
Is there any way to upload a pic file into flatnotes? 

### ISSUE THREAD

**Issue by qianhd** [dullage/flatnotes#126]
When i drag a pic into flatnotes in chrome. it's alway insert a large of garbled characters( is that base64 code of pic ?  i don't know)?.  
I wordering is there any way to upload a pic file, and return back a url, maybe like  "./image/xxx.jpg", and then i can insert into markdown editor.

**Comment by dullage** [comment]
> is that base64 code of pic ?

That's correct.

I appreciate it's not ideal and I would like to improve it at some point. Please go and give a thumbs up to [this suggestion](https://github.com/dullage/flatnotes/issues/45). It's the 2nd most popular suggestion now and the one that affects my own personal use the most so I'm hoping to get onto it soon.
