### ISSUE TITLE
Show more than 5 on home page?

### ISSUE THREAD

**Issue by poblabs** [Dullage/flatnotes#13]
This is great and I think will solve my folder full of .md notes and make it easier to manage them. 

Is it possible to display more than 5 of the most recent on the home page? 

Or maybe another page (or a config option) to show all notes? Maybe sorted by recently changed?

**Comment by poblabs** [comment]
@Dullage looks like this tweak isn't working in the new release anymore. If I change the getNotes limit to 20, it works on front page but not on the A-Z list. Any tips on how to replicate this with the latest version?

**Comment by poblabs** [comment]
Think I found it. In App.vue under NoteList, changing this seems to have worked `:num-recently-modified="25"`

**Comment by Dullage** [comment]
> Think I found it. In App.vue under NoteList, changing this seems to have worked `:num-recently-modified="25"`

I was just coming here to point you in this direction. That's the ticket, glad you found it.
