### ISSUE TITLE
Notes are being identified as updated incorrectly 

### ISSUE THREAD

**Issue by romu70** [dullage/flatnotes#130]
Each time I quit a note to get back to the list, I see the orange animation, I guess it’s the index refresh. But this behaviour impacts negatively the responsiveness of the app because, with my less than 100 notes, it tools 3s at least to display the list of the notes.

It would be great if the index refresh could occur in the background, or if the back action could use the browser cache instead.

**Comment by rprtr258** [comment]
For some reason reindexing happens each time I search. That makes searching incredibly slow.

**Comment by dullage** [comment]
When you say it's re-indexing, are you seeing logs to indicate that certain notes have been identified as updated? e.g.

```bash
2023-10-16 15:54:17 [INFO]: 'keepalived.md' updated
```

**Comment by dullage** [comment]
Hmm, interesting. Just checked my own logs and I'm also seeing a handful of notes being updated every time. I'll do some digging.

**Comment by dullage** [comment]
Problem found. This should be resolved in [v3.3.1](https://github.com/dullage/flatnotes/releases/tag/v3.3.1). Please let me know if not.
