### ISSUE TITLE
How to solve the problem of garbled characters?

### ISSUE THREAD

**Issue by culilaren** [dullage/flatnotes#137]
As with the title
![image](https://github.com/dullage/flatnotes/assets/111490317/172743e2-98f0-4b2b-94e7-8ef4b2bc0155)

**Comment by culilaren** [comment]
installed in unraid, version 6.11.5, browser Edge.

**Comment by dullage** [comment]
Well, this is odd. I have some questions that may help:

1. Is this a brand-new install or have you updated an existing one?
2. It looks like there is emoji content in the search box. How was that entered?
3. What language is your device set to?
4. Do you see the same issue viewing your instance on other devices?
5. Do you see the same issue viewing the [demo site](https://demo.flatnotes.io)?
6. Are you able to try in a different browser?
7. If you read a note outside of flatnotes (i.e. opening up the .md file), what does the content look like?

**Comment by dullage** [comment]
Closing as stale.
