### ISSUE TITLE
Shadow / glow in code block when using WYSIWYG on dark theme

### ISSUE THREAD

**Issue by arseniov** [dullage/flatnotes#138]
Hi,
I've noticed that when using the WYSIWYG editor and inserting a code block with any notation while in dark theme, there is a sort of backdrop shadow / glow around all characters that makes it very difficult to read and edit.
Once saved and previewed outside the editor, the shadow disappears and the text is fully readable while maintaining the chosen code block notation.

Attaching some examples

Thanks for your outstanding work on this project!

Zoomed in:
![image](https://github.com/dullage/flatnotes/assets/83009979/66e9921d-a2b5-4ee3-9dc3-a497c8bb936c)

Example dark theme (affected):
![image](https://github.com/dullage/flatnotes/assets/83009979/5bde06e8-2ea5-4484-8b2c-6238d930f0cc)

Example light theme (not affected):
![image](https://github.com/dullage/flatnotes/assets/83009979/a538beb1-c7d6-429f-b756-fd4932bdcc32)

Preview out of editor (not affected):
![image](https://github.com/dullage/flatnotes/assets/83009979/178353fc-989e-40b7-b8ec-0733940ecd24)

**Comment by dullage** [comment]
Odd! Seems to be [a quirk of the PrismJS syntax highlighter](https://stackoverflow.com/questions/65099537/how-to-turn-off-text-shadow-in-a-prismjs-css-theme). I've overridden this CSS property now so it will be resolved in the next release.

If you don't want to wait you can use the `:develop` Docker tag although please note that this includes an unreleased typography revamp and #14 (wikilink support).

**Comment by arseniov** [comment]
Thanks @dullage!

**Comment by dullage** [comment]
A fix for this has now been released in version 3.6.0.
