### ISSUE TITLE
Implement wikilinks style links to other notes

### ISSUE THREAD

**Issue by poblabs** [dullage/flatnotes#14]
Hi again. Are something [like wikilinks](https://python-markdown.github.io/extensions/wikilinks/) in your plan for future updates?

**Comment by Dullage** [comment]
@poblabs - Nothing planned but I like the idea. I'll leave this as an open suggestion for future consideration.

**Comment by dullage** [comment]
This should be possible using the Toast Editor's [custom HTML rendering functionality](https://github.com/nhn/tui.editor/blob/master/docs/en/custom-html-renderer.md) e.g. turn `[[My Note]]` into a link to `/note/My%20Note`

Renaming notes should also be considered. This could be handled if renaming via flatnotes but if renamed outside of flatnotes (something I'd like to carry on supporting) we'd have no way of knowing.

**Comment by dullage** [comment]
Thanks to @trescenzi, this feature is now available in the develop branch. If anyone is interested in giving it a go before it is officially released they can use the Docker tag `:develop`. It would be great to get some early beta testers.

**Comment by dullage** [comment]
As of version 3.6.0, wikilinks are now supported. Thanks @trescenzi 👍
