### ISSUE TITLE
Icon for PWA

### ISSUE THREAD

**Issue by lokesh-krishna** [dullage/flatnotes#140]
Presently, the favicon seems to get placed on a white background to be used as the icon for the PWA.
Would it be possible to get a dedicated PWA version of the icon?

![Screenshot_20231205-121037~2](https://github.com/dullage/flatnotes/assets/20235646/ccab0392-7afe-41db-a8ba-0d5aa019ff59)

Vikunja here has an icon for its PWA while Flatnotes doesn't.

**Comment by dullage** [comment]
Hi @lokesh-krishna 👋

flatnotes _does_ have a dedicated PWA icon set, see [here](https://github.com/dullage/flatnotes/tree/develop/flatnotes/src/assets). This said, I can see that Vikunja has a round android-chrome... icons which may explain the difference.

Can you tell me please, where is your screenshot from? Is it Android?

**Comment by lokesh-krishna** [comment]
Hi!
This is from Pixel 6 on Android 14 and the PWA was installed using Chrome 120. Is there any additional information that would help?

I also installed the PWA using Firefox on my tablet that's running Android 13 and did get the proper PWA icon there so I guess Chrome does something differently?

**Comment by dullage** [comment]
Unfortunately I only have one Android device to test on and it's fine on that. That said, I think I know what the problem is.

I've made a test change to the demo site (https://demo.flatnotes.io). Can you please try installing that as a PWA and see if you see a difference.

**Comment by lokesh-krishna** [comment]
This does result in a proper icon!
