### ISSUE TITLE
Default Page

### ISSUE THREAD

**Issue by modem7** [dullage/flatnotes#141]
Would it be possible to have a way to set the default landing page when the site is opened?

I've noticed that some of my users are unsure how to navigate the site as they don't immediately notice the "menu" button, so it would be beneficial to have the default landing page to "All notes" in some circumstances. 

Even more so if the files are edited outside flatnotes, which don't update the "recently edited" list.

**Comment by dullage** [comment]
If you're using a reverse proxy (e.g. nginx) you could probably just redirect the root path to `/search?term=*&sortBy=1&showHighlights=false` (which takes you to the All Notes page).

You'd never be able to get to the _actual_ home page but maybe that doesn't matter in your use case.

**Comment by MiguelRenato** [comment]
### Creating responsive web layouts grid on first page.

First of all, I would like to thank you for your efforts on this project, which is my favorite, very clean and with everything needed.
Right now I give a grade of 99% to get a grade of 100% I would love to have it responsive web layouts grid on first page with resume.

exemple:
![image](https://github.com/dullage/flatnotes/assets/72361326/4e5ce2c9-09dd-4b37-b27c-3fbd3c3877c8)

**Comment by dullage** [comment]
> ### Creating responsive web layouts grid on first page.
> 
> First of all, I would like to thank you for your efforts on this project, which is my favorite, very clean and with everything needed. Right now I give a grade of 99% to get a grade of 100% I would love to have it responsive web layouts grid on first page with resume.
> 
> exemple project: https://blog.openreplay.com/creating-a-markdown-powered-nextjs-blog-in-under-an-hour/

Hey @MiguelRenato 👋. Thanks for the nice comments. I'm glad you like flatnotes. Please see #57 and give that suggestion a thumbs up to register your interest.
