### ISSUE TITLE
Host Poppins font locally

### ISSUE THREAD

**Issue by prof729** [dullage/flatnotes#145]
It would be great to have the Poppins font hosted locally for the self-hosted option. 
So the application is not depending on google hosting some stuff.

As far as I've checked the source code the lines that can be changed are: https://github.com/dullage/flatnotes/blob/acd3f99804a114e46bed34a76dba1a356ce51382/flatnotes/src/index.html#L35-L40 with the content of the https://fonts.googleapis.com/css2?family=Poppins:wght@400&display=swap with links to local copy of the font.

Thank you!

**Comment by dullage** [comment]
Agreed. I've made this change in [this commit](https://github.com/dullage/flatnotes/commit/e68b259adf734e867e8c11da156216610c4621ff). It will be out in the next release. 👍
