### ISSUE TITLE
Paste multiple screenshots Error

### ISSUE THREAD

**Issue by fernandeusto** [dullage/flatnotes#153]
When you paste an image that you have on the Windows clipboard, it saves it as "image.png" and therefore when you paste another image again, it cannot add it because that name already exists.

![imagen](https://github.com/dullage/flatnotes/assets/87156183/5051e05e-85dc-4b69-b194-6224bf95a3f3)

It should give a different name like "screenshot20240123-174533.png" adding, for example, the date and time, so that the file is not repeated and save ok

Congratulations for the project

**Comment by dullage** [comment]
It _should_ already do this. Uploaded images should use a format similar to this `image-2024-01-29T08-20-16.004Z`. Can I ask what browser you're using?

**Comment by fernandeusto** [comment]
I have tried in EDGE and it works as you say, but in Firefox, it pastes it as "image.png" and therefore you can only paste one image, because then it already exists.

![imagen](https://github.com/dullage/flatnotes/assets/87156183/faf6e019-7b9e-4672-9104-a8900e77340b)

Windows 11 - Firefox last version

Images copied to the clipboard from the Windows snipping tool, or any image on the clipboard

**Comment by dullage** [comment]
Well, this is odd. I use Firefox myself (on Windows 11) and don't see this issue. Can you please take a look at the console messages in dev tools and let me know if you see any errors.

**Comment by fernandeusto** [comment]
This is de container log
```
WARNING: Breaking changes introduced in version 3.x:
  - The port flatnotes uses inside the Docker container has been changed to 8080 (previously 80).
  - To accompany the above change, support for the PORT environment variable has been removed.
  - The note directory inside the Docker container has moved from /app/data to simply /data.
Setting file permissions...
Starting flatnotes as user 1026...
2024-01-30 11:47:15 [INFO]: Creating new index
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     172.29.0.1:50746 - "GET / HTTP/1.1" 200 OK
INFO:     172.29.0.1:50746 - "GET /src.dfee3e16.css HTTP/1.1" 200 OK
INFO:     172.29.0.1:50752 - "GET /src.ddcda8f6.js HTTP/1.1" 200 OK
INFO:     172.29.0.1:50752 - "GET /apple-touch-icon.cb3e6a74.png HTTP/1.1" 200 OK
INFO:     172.29.0.1:50746 - "GET /favicon-32x32.7917f576.png HTTP/1.1" 200 OK
INFO:     172.29.0.1:50752 - "GET /api/config HTTP/1.1" 200 OK
INFO:     172.29.0.1:50752 - "GET /api/search?term=*&sort=lastModified&order=desc&limit=5 HTTP/1.1" 401 Unauthorized
INFO:     172.29.0.1:50776 - "POST /api/token HTTP/1.1" 200 OK
INFO:     172.29.0.1:50776 - "GET /api/search?term=*&sort=lastModified&order=desc&limit=5 HTTP/1.1" 200 OK
INFO:     172.29.0.1:50804 - "POST /api/attachments HTTP/1.1" 200 OK
INFO:     172.29.0.1:50804 - "GET /attachments/imagen.png HTTP/1.1" 200 OK
INFO:     172.29.0.1:50804 - "POST /api/attachments HTTP/1.1" 409 Conflict
```

I have set up a new flatnotes docker on another server and I have tried again from another PC on another network and the result is the same, it always pastes as "image.png"

To capture the piece of image on clipboard, in Windows 11, I press "windows key" + "shift" + "S" and crop the image, then I enter flatnotes and press "CTRL" + V to paste. It paste always as "imagen.png" and the next paste of any note give error "alredy exist imagen.png"

![imagen](https://github.com/dullage/flatnotes/assets/87156183/cd835c64-2379-4337-99e4-4c30e6370efe)

**Comment by dullage** [comment]
Ah, I see the issue. My naming logic only kicks in when the image name is "image.png" which is the default name given to screenshot pastes. It appears this is language dependent as yours is "images.png" (which makes sense). 

I'll need to see if there's a more robust way I can detect screenshots.

**Comment by fernandeusto** [comment]
The error continues for me in Windows 11 with Firefox when pasting from the clipboard

Sorry, this project looks good but I'm back to obsidian

**Comment by dullage** [comment]
The fix for this hasn't made an official release yet and is currently only available when using the `develop` tag. Perhaps this explains what you're seeing?
