### ISSUE TITLE
Add more options to edit toolbar

### ISSUE THREAD

**Issue by fernandeusto** [dullage/flatnotes#155]
Please add option in edit toolbar to set:

- Foreground text color 
- Background text color
- Underline text
- Clear text formating
- Text alignement (Left,right,center,justified)

![imagen](https://github.com/dullage/flatnotes/assets/87156183/7a2a5aff-a302-46e7-9bdb-15a599c32361)

**Comment by dullage** [comment]
Unfortunately, these options are not supported by the markdown spec. I appreciate that markdown also supports HTML formatting but this would be against the minimal approach of flatnotes. For these reasons, this isn't something I'd look to implement. I hope you understand.
