### ISSUE TITLE
WARN when using "docker-compose image -q"

### ISSUE THREAD

**Issue by Toixinhell** [dullage/flatnotes#156]
When using the command:

`docker-compose images -q `

I get following warning:

`WARN[0000] The "D" variable is not set. Defaulting to a blank string.`

Could not find the D variable anywhere. Is this a bug or how could I mitigate this warning?

**Comment by dullage** [comment]
I'm going to have a wild stab in the dark here and guess that a value in your docker compose file includes "$D" which docker compose thinks is a variable. If so, you can escape it by replacing it with "$$D".

**Comment by Toixinhell** [comment]
oh I see. there was a password in my docker-compose with "$D" in it. Thank you for the insight.
