### ISSUE TITLE
Numbered Lists issues.

### ISSUE THREAD

**Issue by HidYn** [dullage/flatnotes#157]
First of all thank you for your work on this project it's fantastic. 

I'm in the middle of moving all my notes from Joplin to flatnotes and I think I've come across an issue with the numbered line feature.

If I take the attached note as an example the numbered list doesn't continue after 3. and it displays 4. and 5. as 1.

[WinGet.md](https://github.com/dullage/flatnotes/files/14164737/WinGet.md)

I have tested the above in dillinger and joplin and both display as I would expect and continue to 4. and 5.

**Comment by dullage** [comment]
Hi @HidYn 👋. Glad you like flatnotes.

I've had a look and it appears this is the standard behaviour of the markdown editor I'm using ([ToastUI Editor](https://ui.toast.com/tui-editor)) which means unfortunately it's out of my control. Sorry I can't help further, hopefully you can work around it.

**Comment by dullage** [comment]
Great, thanks @HidYn. I'll keep an eye on that issue.
