### ISSUE TITLE
[Feature Request] Folder structure

### ISSUE THREAD

**Issue by Err0r0815** [dullage/flatnotes#160]
**Feature Request:**

it would be a nice feature if you could add the notes to an folder.
in case if u dont remember any word to find it, you could look into the folder with the main topic.

e.g. you created a note with install instructions for a webserver, but dont remember wich one but you know it was on linux.
so you can look in the folder linux an look threw the notes in this folder.

**even better would it be to use some kind of "tags" , that example note could be in the folder "webserver" and "linux" for example**

thanks & greetings
keep up the nice work :)

**Comment by dullage** [comment]
Hey @Err0r0815 👋

flatnotes _does_ have tagging functionality, it's just not very well signposted at the minute. I hope to improve this. 

In the meantime, check out the [wiki page](https://github.com/dullage/flatnotes/wiki/Tagging).

**Comment by Err0r0815** [comment]
Would be nice if the tags show up as "folders" an you can navigate threw all the notes with the tag.
like a tree structure or something.

i have another question, dont know if i could ask it here or create another thread.
is there a way to migrate from other note taking apps like one note or evernote to flatnote? would be a charme :-)

**Comment by dullage** [comment]
> Would be nice if the tags show up as "folders" an you can navigate threw all the notes with the tag.
like a tree structure or something.

I'd certainly like to add better visibility of available tags. See #35.

> i have another question, dont know if i could ask it here or create another thread.
is there a way to migrate from other note taking apps like one note or evernote to flatnote? would be a charme :-)

There's no direct migration path but if the other app allows you to export to markdown then you can just add the exported markdown files to the flatnotes directory and it'll pick them up. Even if the other app doesn't allow markdown support there may be a way. For example, maybe you can export to HTML and use another tool to convert to markdown.

**Comment by Err0r0815** [comment]
okay, at the moment my workaround is, that the first word in the title  of the note is the "folder" name


the migration is done. i converted all to docx files and then to markdown files.
after that a few fixes with scripts, but worked fine.
