### ISSUE TITLE
Where are all the Notes in the Server File Manager?

### ISSUE THREAD

**Issue by KosmicDaKerbal** [dullage/flatnotes#168]
I would like to know where you could find your notes from the server's file manager (like thunar). i searched the /var/lib/Docker folder, but i couldnt find anything which contained my note. can someone help me as to where the files are located?

**Comment by dullage** [comment]
Can you please share the docker-compose or docker run you used (obfuscating any secrets).

**Comment by KosmicDaKerbal** [comment]
> Can you please share the docker-compose or docker run you used (obfuscating any secrets).

i just ran the example docker compose script
docker run -d \
  -e "PUID=1000" \
  -e "PGID=1000" \
  -e "FLATNOTES_AUTH_TYPE=password" \
  -e "FLATNOTES_USERNAME=user" \
  -e "FLATNOTES_PASSWORD=changeMe!" \
  -e "FLATNOTES_SECRET_KEY=aLongRandomSeriesOfCharacters" \
  -v "$(pwd)/data:/data" \
  -p "8080:8080" \
  dullage/flatnotes:latest

just replaced the user and password and secret key to my own.

**Comment by dullage** [comment]
Ok great. So `-v "$(pwd)/data:/data"` means that Docker should have created a "data" directory in the same directory as the docker-compose.yaml file. That's where you should find the notes.

**Comment by KosmicDaKerbal** [comment]
> Ok great. So `-v "$(pwd)/data:/data"` means that Docker should have created a "data" directory in the same directory as the docker-compose.yaml file. That's where you should find the notes.

I found it! it was in my /root directory, since i ran the command from the root terminal. its not normally accessible from thunar, so i got a little bit confused.
thank you so much!
