### ISSUE TITLE
Number List issue

### ISSUE THREAD

**Issue by PradeepKumarBose** [dullage/flatnotes#169]
Describe the bug

To Reproduce
1. Just simpley include numerList and add more 

The list will be in the correct order.

![image](https://github.com/dullage/flatnotes/assets/29145245/81c77b68-c0f3-42d5-a367-a7d292cd1a36)

**Comment by dullage** [comment]
Hi @PradeepKumarBose. This is by design and is [part of the Markdown spec](https://daringfireball.net/projects/markdown/syntax#list). You can use any numbers in any order and the Markdown renderer will correct them for you.
