### ISSUE TITLE
Add config option to show "Recently modified" in read-only mode

### ISSUE THREAD

**Issue by anantone** [dullage/flatnotes#170]
I'm running two instances on the same data folder, one with password auth for myself to edit notes, the other in read-only mode for public viewing. Once logged in with password, I can see "RECENTLY MODIFIED" notes under the search bar of landing page. In read-only mode, I can't. Is it possible to modify this?

Thank you! Great app, love the simplicity and efficiency!

**Comment by dullage** [comment]
Reopening to leave as an open suggestion.

**Comment by anantone** [comment]
I thought you'd done it? It certainly works on my instance now...

**Comment by dullage** [comment]
> I thought you'd done it? It certainly works on my instance now...

Oh! Looks like a bug that slipped into v5! What I'll probably do is implement this config option rather than fix the bug. That keeps things flexible. I'll keep this open as a reminder.
