### ISSUE TITLE
Install uvloop alongside Uvicorn for performance improvements

### ISSUE THREAD

**Issue by Code-Otto** [dullage/flatnotes#175]
The Uvicorn webserver used by Flatnotes supports two asynchronous event handlers for networking: `uvloop` and Python's built-in `asyncio`

`uvloop` is a performance-focused reimplementation of `asyncio` written in Cython and the recommended choice by Uvicorn developers, as mentioned at [Uvicorn's homepage](https://www.uvicorn.org/):

> · the event loop uvloop will be installed and used if possible.
· uvloop is a fast, drop-in replacement of the built-in asyncio event loop. It is implemented in Cython. Read more [here](https://uvloop.readthedocs.io/).
· The built-in asyncio event loop serves as an easy-to-read reference implementation and is there for easy debugging as it's pure-python based.

However currently it is not listed as a dependency in the pipfile and does not get installed at the produced Flatnotes Docker images, where Uvicorn falls back to using `asyncio`

I've done some testing and here's the idle CPU usage of Flatnotes in my armv7 RPi, both with and without `uvloop`:
```
CONTAINER ID   NAME               CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
b67416769f9c   mytinytodo         0.01%     1.023MiB / 967.2MiB   0.11%     390kB / 0B       10.1MB / 8.19kB   9
55ac3e0c2840   metube             0.04%     3.641MiB / 967.2MiB   0.38%     131MB / 6.71MB   318MB / 787MB     11
279dc758531d   flatnotes          0.86%     33.75MiB / 967.2MiB   3.49%     1.31kB / 0B      5.47MB / 36.9kB   2
cf591b2de849   flatnotes-uvloop   0.63%     30.4MiB / 967.2MiB    3.14%     1.24kB / 0B      868kB / 24.6kB    6
```
Both them actually fluctuate a lot however I've found the `uvloop`-powered one to constantly use less CPU than `asyncio`
_(As a curiosity: mytinytodo is a PHP app using the Lighttpd webserver, you can find the used Dockerfile under my Github profile, and metube is a Python3 app using the aiohttp server)_

I haven't conducted a proper stress test to also confirm a performance improvement under heavy load though, but seems reasonable that it would improve too

Now I'd like to have made this a pull request however I'm having trouble with re-locking the pipfile (pipenv throws a terribly long error message and a complaint about invalid syntax) and have been unable to work it around so I'll just tell you the what the two required small changes are:
 - Add `uvloop` as a dependency to the pipfile
 - Add the `--loop uvloop` argument to the entrypoint script to make sure Uvicorn is picking up uvloop

Thanks for your attention

**Comment by dullage** [comment]
Odd, I am specifying uvicorn[standard] in the pipfile, uvicorn docs seem to indicate this is enough but you're right, it doesn't look like uvloop is being installed by pipenv. I'll do some digging.

![image](https://github.com/dullage/flatnotes/assets/16575268/b7b81219-0687-4549-90eb-9f2a7b8008da)

**Comment by dullage** [comment]
Ah, looks like uvloop doesn't support Windows and I develop (and lock the Pipfile) on Windows. I might have a look at using a devcontainer so that I can develop on Linux.

**Comment by dullage** [comment]
The develop branch and the latest develop Docker image now includes a Pipfile.lock that was locked on Linux (using a devcontainer). I can now see that uvloop is installed as expected.

**Comment by Code-Otto** [comment]
Tested working. Great, thank you!
