### ISSUE TITLE
Add ability to change port number

### ISSUE THREAD

**Issue by aguileraGit** [dullage/flatnotes#176]
Hello @dullage,
Per my [Docker issue](https://github.com/dullage/flatnotes/issues/173), I modified your Dockerfile and entrypoint.sh to add the ability to change the port on which the uvicorn server listens on. README shows how to use it. There's a bit in there that should go in the Wiki.

I wasn't thinking and I just plugged down your repo, made changes, and pushed to a new repo I created. If you approve the changes, I can fork your repo or see if I can push to a new branch.

See changes [here](https://github.com/aguileraGit/flatnotes-dockerUpdates/commit/252d5e4547e3820281792473e5b2decbaed0abf3).

**Comment by dullage** [comment]
Hi @aguileraGit, thanks for giving it a go. I can see a benefit in this so I have pushed [a similar change](https://github.com/dullage/flatnotes/commit/52bca5919d0ad0d8f175c4ba9abc22f0be9a6793) (with a few tweaks) that will be in the next release. I hope this helps.

**Comment by aguileraGit** [comment]
That's awesome! I'll keep an eye out for the next release. I really appreciate this addition and project in general.
