### ISSUE TITLE
[Feature] Disable TOAST UI Editor usage statistics

### ISSUE THREAD

**Issue by pweth** [dullage/flatnotes#184]
Hi,

TOAST UI Editor makes Google Analytics calls which is not preferable for self-hosted instances of flatnotes.

This can be disabled using a property, per the [README](https://github.com/nhn/tui.editor/blob/0c5c11bac0b9954e2cac2ff2a081ce8c80a5f14d/apps/react-editor/README.md): 
```js
<Editor
  ...
  usageStatistics={false}
/>
```

If disabling by default is not a viable option, maybe this could be controlled using a flatnotes environment variable?

Please let me know your thoughts.

Thanks!

**Comment by dullage** [comment]
Hi @pweth. I'm happy to make this change. I'm currently working on a complete rebuild of the UI and I've [just made this change](https://github.com/dullage/flatnotes/commit/e290ef9d721af78feef449f2ca9117750b120943) in that branch. Once that gets merged, it'll come into effect.

**Comment by pweth** [comment]
That's great, thank you very much!
