### ISSUE TITLE
KEY clarification

### ISSUE THREAD

**Issue by MarcS1975** [dullage/flatnotes#204]
Thank you for this excellent project. I love the minimalist approach !
One question. I am loging in via username and pwd.
Do I need to define a SECRETKEY if I dont use the TOTP_KEY functionality?
As I understand the SECRETKEY is only used if the QR-code is not working. Or did I misunderstand?

**Comment by dullage** [comment]
Hey @MarcS1975. I'm glad you like it 👍

The `FLATNOTES_TOTP_KEY` is used for TOTP. `FLATNOTES_SECRET_KEY` is used to generate access tokens, which _is_ used by the password auth. Have a look at the [wiki article](https://github.com/dullage/flatnotes/wiki/Environment-Variables#flatnotes_secret_key) for more info.
