### ISSUE TITLE
support for math expressions?

### ISSUE THREAD

**Issue by rahulsanjay18** [dullage/flatnotes#205]
This might be asking too much, but would it be possible to have some sort of KaTeX math renderer?

**Comment by dullage** [comment]
It's been asked before. The reason I'm hesitant is similar to the reason I rejected a PR for UML support recently. The toast-ui editor I'm using looks like it's no longer maintained, and so I'm likely to need to look for (or build) alternatives at some point in the future. The more the editor supports, the harder it will be to find a replacement.

There's already a separate issue to track LaTeX/KaTeX support (#61) so please go give that a thumbs up to show your interest.
