### ISSUE TITLE
Building docker image fails on MacOS ARM chip

### ISSUE THREAD

**Issue by pbogre** [dullage/flatnotes#208]
Using the main Dockerfile from the develop branch fails when trying to build the image. I am on MacOS with a Macbook Pro M1, which means that docker runs on the linux engine.

Here's the error that I get:
```
Dockerfile:22
--------------------
  20 |
  21 |     COPY client ./client
  22 | >>> RUN npm run build
  23 |
  24 |     # Runtime Container
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

This was simply fixed by adding the line 
```Dockerfile
RUN npm install -D sass
```
right before `npm ci` is executed.

Not sure if this problem is relevant to anyone else trying to build flatnotes.

**Comment by dullage** [comment]
Odd, I've not seen this myself when building on Windows (WSL2) or Linux. I don't have access to a mac to troubleshoot, so I'll close this off, but at least it will act as a reference in case anyone else has this issue.
