### ISSUE TITLE
Notes tiled ".", ".." or containing URL/percent encoded characters are innaccesible after creation

### ISSUE THREAD

**Issue by danielmcmillan** [dullage/flatnotes#209]
When a note is created with title "." and "..", they appear on the filesystem as "..md" and "...md" respectively. This is normal, but then trying to access those via the browser will take you to "/note/" or "/". They are still accessible via API.

When a note is created containing a URL encoded character, such as "a%3Db" (decodes to a=b), it is treated as a literal string as expected and appears on the filesystem as "a%3Db.md". However, when trying to access the note from the browser at the expected URL with the percent symbol being encoded "/note/a%253Db" the note cannot be found.
The API request being sent is for "a=b", so it may be that the name from the URL is incorrectly being decoded a second time. The note can be accessed by double-encoding the note name in the url "/note/a%25253Db".

**Comment by dullage** [comment]
Thanks. Fixed in [this commit](https://github.com/dullage/flatnotes/commit/510a5f4e6576245d4e41f7267d8b6561d68d7a67) and will be in the next release.
