### ISSUE TITLE
Search Highlight Missing Next Level Navigation

### ISSUE THREAD

**Issue by dev20242025** [dullage/flatnotes#211]
Hi,

I tried https://demo.flatnotes.io/search?term=test and highlight works fine but it failed to have navigation arrows or button to further navigate and highlight after clicking the search result

There is a difference between reading the text directly or coming through the search. When we search for a keyword, it should be highlighted in the opened document and also need to have arrows or buttons to go or hit next match in the same document as multiple occurences in the same document is possible

Also, type-ahead with number of matches found is required while typing

Please consider

Thanks

**Comment by dullage** [comment]
Thanks for the suggestion. This is similar to #97 so I will close this as a duplicate. Please give the other suggestion a thumbs up to show your interest.
