### ISSUE TITLE
[Feature Request] Add ability to set .flatnotes location.

### ISSUE THREAD

**Issue by adriel-tech** [dullage/flatnotes#215]
Hello,

I use flatnotes on a server which also has syncthing syncing my notes to other devices. The .flatnotes folder is inconvenient
for this use case as it is always writing and syncing. It would be nice to be able to set the location of the .flatnotes folder to somewhere outside of my note folder root.

Thanks for the nice app, it was hard to giving up folders, but flatnotes runs well.

**Comment by dullage** [comment]
Hey @adriel-tech, glad you like flatnotes, and thank you very much for the sponsorship, I really appreciate it 👏.

Are you using Docker to run flatnotes? If so, it is already possible to do what you're suggesting, as I do the same myself. The [example docker compose](https://github.com/dullage/flatnotes?tab=readme-ov-file#example-docker-compose) shows how this can be achieved.

**Comment by adriel-tech** [comment]
Thanks for the reply.

I am using podman on NixOS the example in the docker compose does not work for me,  my problem is probably due to NixOS spaghetti code. 

looking over the example docker compose, you are passing a local ./index into /data/.flatnotes

```
# - "./index:/data/.flatnotes"
```

I think my issues is that flatnotes always expects .flatnotes to be created in /data and it cannot be placed somewhere else instead of the notes root folder. My notes are stored in /mnt/Notes which is synced with syncthing. Using podman the .flatnotes  folder is always made in /data/.flatnotes. Since /mnt/Notes is mounted inside the podman container as /data, .flatnotes is created which is then synced by syncthing.

Being able to mount my notes to /data/notes would solve my problem or /data/.flatnotes being placed elsewhere like /cache.

I did find a work around for my problem which is just telling syncthing to ignore .flatnotes, which I should have done before bothering you with this.

**Comment by dullage** [comment]
I'm not familiar with Podman, but this is certainly possible with Docker. In my case, I mount my `.flatnotes` directory to a location on my SSD and I mount my notes to a directory on my (slower) storage array.

Anyway, I'm glad you found a solution.

**Comment by Soiltasun** [comment]
Hi @dullage - tried this on Unraid via their docker interface and although paths were setup as indicated, they were not respected as separate

Unraid docker setting for respective paths
![Image](https://github.com/user-attachments/assets/47454675-c1f5-46be-812a-8f0734820e2d)

`appdata` showing dates of install (1-31 & 2-1) trying to set it all up.
Then added the separate `remotes` path, which subsequently ignored this as `/index` path
![Image](https://github.com/user-attachments/assets/60cf5c81-8eda-48a0-8fdd-75d22b206117)

`remotes` showing dates being updated to current (2-3 & 2-5), including the writing of `.md` files
![Image](https://github.com/user-attachments/assets/b6e4d391-8cc4-4e18-b7f4-2641dbc53595)

Flatnotes works as intended overall, with the bonus of utilizing an existing backup scheme on the `remotes` drive, but would be interested to gain path separation as mentioned re: SSD - am happy to try a second instance to help troubleshoot
