### ISSUE TITLE
Keyboard shortcut for preview

### ISSUE THREAD

**Issue by marcxm** [dullage/flatnotes#216]
Any option to add keyboard shortcut (similar to what **CTRL+ENTER** does to quick save) to toggle between edit and preview modes? this is since we don't change markdown to HTML on the fly (Obsidian case comes to mind), nor do we have preview space opened next to editor (Hedgedoc and similar).
Maybe such keyboard shortcut would be something like **ALT+V**, so it doesn't conflict with browser printing shortcut? (**ALT+P** is probably not the best choice either, as it conflicts with menu option in Firefox, for example).

Thanks in advance for checking. Stay awesome!

**Comment by dullage** [comment]
Hey @marcxm. You can press `e` to enter edit mode and `Esc` to exit edit mode. Or are you describing these modes:
![image](https://github.com/dullage/flatnotes/assets/16575268/d30ff851-e7c6-405f-b383-298ff4ea6f16)

**Comment by marcxm** [comment]
Yes, I was thinking about "Preview" mode shortcut, but I can see that "Esc" works just as well. Couldn't find shortcuts list on a page. Thank you.

**Comment by dullage** [comment]
I need to do a better job making these shortcuts discoverable in the UI. In the meantime, [the wiki page](https://github.com/dullage/flatnotes/wiki/Keyboard-Shortcuts) is the best reference.
