### ISSUE TITLE
Add support to download the notes as PDF

### ISSUE THREAD

**Issue by absoluteval** [dullage/flatnotes#218]
Hey @dullage - You've any plans to support downloading the notes as PDF?

**Comment by kolinblue** [comment]
@absoluteval you might want to try https://github.com/barelyhuman/mark in the meantime. Browser side only, exports markdown to pdf and maybe some other formats. A copy & paste from flatnotes could do the trick.

**Comment by kolinblue** [comment]
> Hey @kolinblue - Thanks for sharing. Just tried it and the downloaded PDF is pixelated.
> 
> Here it is: [Screenshot from 2024-07-17 13-55-47](https://github.com/user-attachments/assets/19d98b57-5862-442f-996f-3ea460f09ecc)

Can't help you with that, I'm afraid. Only other markdown editor that exports markdown-to-pdf that I know of would be [stackedit](https://github.com/benweet/stackedit). 

[menote](https://github.com/eteplus/menote) can display the source of a markdown note in html format side by side, that might be able to get you closer, but it won't do pdf directly.

**Comment by dullage** [comment]
> Hey @dullage - You've any plans to support downloading the notes as PDF?

No plans at present but I'll keep this open as a suggestion to track demand.

**Comment by absoluteval** [comment]
@dullage - Just a thought. If we enable the full screen preview mode, can we off-load the heavy lifting of generating the PDF to the browser's in-built print functionality?

**Comment by dullage** [comment]
> @dullage - Just a thought. If we enable the full screen preview mode, can we off-load the heavy lifting of generating the PDF to the browser's in-built print functionality?

Great point 👍

I've just pushed [a commit](https://github.com/dullage/flatnotes/commit/35528808ddff7dc4aaf4f3127f9785c298cf3489) that will exclude the navbar and buttons when printing a note. It'll be in the next release, or you can pull the Docker image with the `:develop` tag to try it out sooner.

**Comment by absoluteval** [comment]
Thanks @dullage - Let me give it a try.

**Comment by absoluteval** [comment]
LGTM.
