### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by mangoose20026** [dullage/flatnotes#219]
i went to the demo url and type "the" in the search and pres enter and it does nothing.

**Comment by dullage** [comment]
When you say it does nothing, do you mean that it runs the search but returns no results? Or does it literally do nothing (i.e. you're still on the home page)?

For me, it's the former:
![image](https://github.com/user-attachments/assets/eac36a8c-db55-45d5-802a-f5cc3aa2ad20)

Which is expected, as "the" wouldn't be indexed as it's a "[stop word](https://en.wikipedia.org/wiki/Stop_word)".

**Comment by mangoose20026** [comment]
got...now searched for text vestibulum ...it beautifully highlight the given text but the highlight goes off when i clicked the note, also no arrows or buttons to navigate the keyword searched for.

2 level search navigation would be really helpful..also status with matches found would be helpful...

please kindly import few documents in simplenote and you will find the highlight, no of matches, arrows for easy navigation

**Comment by dullage** [comment]
There's an existing suggestion for what you're describing (see #97). I have no current plans to implement that feature, but please go and give that issue a thumbs up to log your interest.
