### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Dullage** [Dullage/flatnotes#22]

**Comment by dsfsdbvxc** [comment]
+1

**Comment by Dullage** [comment]
Update: I have a local branch open that restructures the colours into custom CSS properties. I have the core flatnotes colours switching between light and dark mode and most of the preference saving/loading done. 

Unfortunately the task to style the markdown editor is bigger than I initially thought. The ToastUI editor does come with a dark theme but it clashes with the flatnotes theme so will need a full review.

**Comment by dominikheinz** [comment]
I agree, a dark mode would be a great addition to this wonderful app.
Looking forward to it in the future! :)

**Comment by Dullage** [comment]
A pre-release is now available that includes a dark theme 🎉. Please see [the release notes for v3.0.0-rc.3](https://github.com/Dullage/flatnotes/releases/tag/v3.0.0-rc.3) for information on how to switch to the pre-release which **includes some breaking changes**.

If you spot anything that doesn't look right when using the dark theme please let me know. Equally, please let me know if it's looking good. Ideally I'd like to have a couple of other users using it before full release.

**Comment by Dullage** [comment]
A dark theme is now available in [v3.0.0](https://github.com/Dullage/flatnotes/releases/tag/v3.0.0).
