### ISSUE TITLE
1Password Autocomplete Issue

### ISSUE THREAD

**Issue by maccuaa** [dullage/flatnotes#224]
When using 1Password to autocomplete the fields on the login page, it seems to get tripped up because the input fields don't have `id` attributes. Specifically the OTP field. 

When I added `id` attribute to all 3 elements, I was able to successfully with 1Password.

I can open a PR with a fix but this is essentially all that's needed:

<img width="714" alt="image" src="https://github.com/user-attachments/assets/51528d1b-f38a-4e82-be50-4ae3869342c1">

**Comment by dullage** [comment]
Thanks for reporting this and for bringing the solution as well. It probably doesn't help that there aren't any input labels. I've added these ids, and they will be in the next release.
