### ISSUE TITLE
Add Ctrl + S as a shortcut key to save the current note.

### ISSUE THREAD

**Issue by GuoJiaxing1997** [dullage/flatnotes#225]
Add Ctrl + S as a shortcut key to save the current note.
Now Ctrl + S is to save .html.

**Comment by dullage** [comment]
I'd love to do this, but unfortunately it's used by the editor component for strike-through. The only way I can override it is to disable all keyboard shortcuts in the editor (things like CTRL-B for bold) and then manually re-implement them. So for now, we'll have to make do with CTRL-Enter to save (available in the latest version).

**Comment by GuoJiaxing1997** [comment]
got it, thanks!
