### ISSUE TITLE
Ticking boxes in WYSIWIG mode

### ISSUE THREAD

**Issue by MarcS1975** [Dullage/flatnotes#226]
Flatnotes is fantastic for quick todo lists. Creating tick boxes for todo lines is great. But it would be even better if we could add/remove the tick in WYSIWYG mode. Currently, I always have to go into "ugly" edit mode to change the box from ticked to unticked.
Would you consider adding this feature?

**Comment by dullage** [comment]
Hi @MarcS1975, to confirm, do you mean the view mode I.e. with edit turned off? Because you _can_ toggle them in WYSIWYG mode (I.e. the tabs at the bottom).

**Comment by dullage** [comment]
Thanks for confirming. This has been suggested before so please go and give [that issue](https://github.com/dullage/flatnotes/issues/158) a thumbs up. 

I did have a brief attempt at implementing this but unfortunately ran into issues (more details on the above issue). I'll take another look when I get a chance.
