### ISSUE TITLE
Second level highlight is not happening

### ISSUE THREAD

**Issue by mangoose20026** [dullage/flatnotes#228]
Ex: https://demo.flatnotes.io/search?term=test

Clicking one of the result, open the page
In that  opened page the term should be highlighted again

This is generally works in many note taking apps
example, app.simplenote.com

however it further have highlight, arrows, status bar with 1/34 to trace the match

please consider

**Comment by dullage** [comment]
Hi @mangoose20026. Unfortunately, I don't have any plans for this at present. 

This is similar to #97 so I'll close this as a duplicate, please go and give that a thumbs up to register your interest.
