### ISSUE TITLE
Tree structure

### ISSUE THREAD

**Issue by woonaval** [Dullage/flatnotes#23]
I know the name is "flat" and you mention this in the design principle... but.. do you have any plans to add a lateral pane with a folder/tree/category structure so we could save the notes in a more ordered way?
Thanks for your work anyway, I love it so far!

**Comment by Dullage** [comment]
Hi @woonaval. I'm very keen to stay away from a hierarchical structure. But, I am looking into adding the ability to "tag" notes which would allow users to achieve something similar. I've just created an issue for it, see #24.
