### ISSUE TITLE
[Proposal] Use shadcn/vue as a collection of UI components

### ISSUE THREAD

**Issue by susomejias** [dullage/flatnotes#234]
I would like the application to use the [shadcn/vue](https://www.shadcn-vue.com/) components, in addition to giving it a more modern touch it would help speed up maintenance and the inclusion of new features in the front part of the application, if any help is needed with this I could help although I haven't touched vue much it shouldn't be much of a problem, thanks

**Comment by dullage** [comment]
Hey @susomejias. flatnotes currently makes use of the PrimeVue component library. What would be the benefit of switching to shadcn? Do you have particular feature in mind?

**Comment by susomejias** [comment]
I didn't know about Primevue, it seems to have a good set of ready-to-use components, although one of the main advantages of using shadcn for example is the block functionality, you have blocks already made for login forms, register forms, Dashboards, etc. 

https://www.shadcn-vue.com/blocks.html

Also, the design line seems a little thinner to me than Primevue, although I understand that it may not be worth the effort vs the benefit 😊

**Comment by dullage** [comment]
That's the key thing, at this stage, I don't see a real benefit. I'm keen to keep flatnotes simple which means limiting new features. So the need for lots of off the shelf components just isn't there.
