### ISSUE TITLE
Question on the feature "Customisable home page"

### ISSUE THREAD

**Issue by CDubs00** [dullage/flatnotes#246]
Under the "Features" section it says "Customisable home page"  I can't seem to figure that out. Id like to change the Title on the search screen, if possible.  Thanks!

(also "Customisable" is misspelled, it should be "Customizable")

**Comment by dullage** [comment]
Hey @CDubs00,

The part you can customise is the  "quick access" section that shows recently modified notes by default. Take a look at [this part of the wiki](https://github.com/dullage/flatnotes/wiki/Environment-Variables#flatnotes_quick_access_term) for details.

> (also "Customisable" is misspelled, it should be "Customizable")

Not here in dear old England my friend 🇬🇧

**Comment by CDubs00** [comment]
> The part you can customise is the "quick access" section that shows recently modified notes by default. Take a look at [this part of the wiki](https://github.com/dullage/flatnotes/wiki/Environment-Variables#flatnotes_quick_access_term) for details.
> 

Ah ok, yes I seen that! Appreciate the response! 
 
> Not here in dear old England my friend 🇬🇧

Carry on then. 😁

thanks for the quick response! I love the simplicity of the app, I’m trying to get my head into a new place where I don’t need folders.
