### ISSUE TITLE
After modifying the website's font, the ordered list misaligns.

### ISSUE THREAD

**Issue by 63936** [dullage/flatnotes#248]
I changed the font by modifying the `index-*.css` file, adding the following CSS:

```
* {
    font-family: "Courier New" !important;
}
```

However, when the ordered list exceeds 10 items, the numbering becomes misaligned in the preview, as shown in the screenshot below.
<img width="608" alt="截屏2024-10-05 00 45 05" src="https://github.com/user-attachments/assets/2a90d647-fe21-467a-88f1-3609de6f6283">

**Comment by dullage** [comment]
Hi @63936. Changing fonts isn't really something that is supported. But by all means give it a go.

The place to change it would be in the tailwind config rather than in the distributed css files. 

Note: Changing the font this way will require you to manually build the site yourself.
