### ISSUE TITLE
[Feature request] Ability to share specific notes

### ISSUE THREAD

**Issue by m-danya** [dullage/flatnotes#249]
When the flatnotes service is password/TOTP protected, it can be useful to "unprotect" some pages with a "Share" button.

For example, I have flatnotes deployed at `notes.mysite.ru` and I want to share a specific note about some topic with my friend or for some group of people. I would like to have a "Share"/"Unprotect" button that will copy the publicly accessible URL of the note to the clipboard. I can think of two ways here: 

1) note is publicly accessible at `notes.mysite.ru/note/some-note` (upd. it will be harder to manage rights for ro/rw than in the following way)
2) a special link is generated for public access for this note, with read-only access: `notes.mysite.ru/note/bfe7964d-611d-49a3-baea-976c6a2e1c18` or `notes.mysite.ru/public-notes/some-note`

Let me know what you think about this feature. Thanks!

**Comment by dullage** [comment]
Hey @m-danya 👋. Note sharing is loosely on the roadmap. It's something I'd use myself. There's already an issue open for it (#21). I'll close this as a duplicate, so please go give that issue thumbs up to register your interest.
