### ISSUE TITLE
Access Security

### ISSUE THREAD

**Issue by MarcS1975** [dullage/flatnotes#257]
Is it possible to add fail2ban to the docker stack as it would reduced the risk of brute force attacks. Since most poeple have their notes exposed publicly. Or are there any other security features already built into flatnotes to protect from attacks?
Many thanks for your consideration.

**Comment by dullage** [comment]
Hey @MarcS1975. I've no plans to add fail2ban to the container but there are some things that can be done. 

Firstly, if you have flatnotes in front of a reverse proxy like nginx then you should be able to use fail2ban with nginx's logs for protection.

With the right config, you may also be able to setup fail2ban to parse the logs from the flatnotes container. This is beyond my knowledge of fail2ban though. 

Lastly, in terms of other brute force protections, you could enable 2FA in flatnotes. 

I hope this helps.
