### ISSUE TITLE
Improve Docker Mount Workflow

### ISSUE THREAD

**Issue by dullage** [Dullage/flatnotes#26]
Currently the user needs to create a `data` folder to map to `/app/data` inside the container and give user 1000 (the flatnotes user) permission to read/write in it. If they don't do this then Docker creates the folder with ownership assigned to root. If that happens, flatnotes doesn't have the ability to write to the directory and crashes.

Perhaps I need to initially run as root, update the folder ownership and _then_ switch to the flatnotes user to run the app.

Suggestions [from Reddit](https://www.reddit.com/r/selfhosted/comments/wvxmaz/flatnotes_a_note_taking_web_app_that_uses_a_flat/):

>You might need to make an env for the user and group ID.

> you can use something like su-exec or s6-overlay to do user masking. do all your startup/init as root and then the last action is to start the app as the env provided uid/gid.

**Comment by norsemanGrey** [comment]
On the same topic you should also "remove" the `/app`  part of the path the user needs to map to. I believe the convention is to expose only single level directory for mapping.

**Comment by Dullage** [comment]
@norsemanGrey - This makes sense and is certainly the convention I've seen for linuxserver.io containers. I'll keep this in mind.
