### ISSUE TITLE
Creating a new note when in edit mode does not clear the note body

### ISSUE THREAD

**Issue by hercules-rockefeller** [dullage/flatnotes#267]
Repro:

* create a note with a title
* save
* click "new note"

expected: clears body of existing note
actual: body is persisted in the new note

notes:

* this does not happen if you toggle off edit before clicking "new note"
* the title field is cleared (as expected)
* the url updates from the `/<note_title>` to `/new` (as expected)
* same behaviour observed when editing an existing note and then creating a new note

**Comment by dullage** [comment]
Is this a duplicate of #266?

**Comment by hercules-rockefeller** [comment]
it is! sorry about that - I did search but didn't find that one (the previous bug - doh)

**Comment by dullage** [comment]
No worries. To save on admin I tend to close issues once they're done rather than when they're shipped. But this can occasionally cause confusion.
