### ISSUE TITLE
Auto-complete when searching by tags is case sensitive but tags are case insensitive

### ISSUE THREAD

**Issue by hercules-rockefeller** [dullage/flatnotes#269]
Tags are case insensitive when defining and matching on searches, but the autocomplete appears to be case sensitive.

- create a note with tag `#work`
- add one or more with variations like `#Work` and `#WORK`
- save
- search by typing in tag `#wor...` and the suggestion is for `#work`
- add a capital `K` suggestion disappears

Searching by any variation of capitalization returns the expected result(s).
This is a very minor (mostly cosmetic) bug, but might be a quick fix to lowercase any search tags prior to retrieving matching tags

**Comment by dullage** [comment]
Thanks @hercules-rockefeller. This is a good shout and an easy fix. It'll be in the next release.
