### ISSUE TITLE
[Request] Improve UX on Ctrl+Z

### ISSUE THREAD

**Issue by m-danya** [dullage/flatnotes#271]
Ctrl+Z on a just-opened note erases all text, which could lead to data loss if user accidentally clicks save.

### Steps to reproduce behaviour
1. Open any exising note
2. Click EDIT
3. Press CTRL+Z
4. Don't press SAVE... or you'll lose your data

### Suggestion
Somehow prevent it

**Comment by dullage** [comment]
Interesting, I've not found this one before. Unfortunately, it's an issue with the embedded Toast UI Editor that flatnotes uses. You can see the same behaviour on [the components demo site](https://ui.toast.com/tui-editor). I'd raise a bug on that repo, but sadly it doesn't look like it's maintained any more.

**Comment by dullage** [comment]
Related issue: https://github.com/nhn/tui.editor/issues/3195
