### ISSUE TITLE
Port 80 permission denied on Synology

### ISSUE THREAD

**Issue by zmeel** [Dullage/flatnotes#28]
Running the docker instance of flatnotes on a Synology box (DS415+) gives the following error even if I set the local port to somthing like 49161. It seems that flatnotes overrules this setting and tries to bind to local port 80 (which is not allowed):
```
ERROR:    [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied
2022-08-26 08:10:06 [ERROR]: [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied
```
Docker is using the bridge network. 

In the Dockerfile I noticed that host (0.0.0.0) and port (80) is mentioned:
```
ENTRYPOINT [ "pipenv", "run", "python", "-m", "uvicorn", "main:app", "--app-dir", "flatnotes", "--host", "0.0.0.0", "--port", "80" ]
```
I'm not sure but I think addition of host (0.0.0.0) and port (80) to the entrypoint forces flatnotes to use the local port 80  on Synology

**Comment by Dullage** [comment]
Hmmm 🤔. As far as I understand it, this entrypoint is run inside the container and so shouldn't affect the port bound _outside_ the container (unless running in host network mode).

I'm unfamiliar with Synology but perhaps if you posted some screenshots of the config you're using I might spot something?

**Comment by zmeel** [comment]
![image](https://user-images.githubusercontent.com/34382336/186870897-a2d12f0d-437d-4d26-80df-0dd44c23704d.png)
![image](https://user-images.githubusercontent.com/34382336/186871028-171be494-2580-4781-8bed-96434cdd6085.png)
![image](https://user-images.githubusercontent.com/34382336/186871106-ccf00876-1967-47fd-bbf3-2db76abb68d2.png)
![image](https://user-images.githubusercontent.com/34382336/186871201-4c616a96-97f3-4d26-971b-aef1e63be0d5.png)
![image](https://user-images.githubusercontent.com/34382336/186871968-b9fc095a-292e-407d-a5f9-bb7bed00c504.png)

**Comment by Dullage** [comment]
I have a theory. It seems that the reason the unprivileged flatnotes user can bind to port 80 (usually a privileged port) inside the container is because Docker sets the `net.ipv4.ip_unprivileged_port_start` value to `0` (i.e. all ports are unprivileged). I wonder if Docker on Synology doesn't do this.

Is there anywhere in the Synology interface to set sysctl values for a conatiner? They're one of the docker run command options so I would expect there is. If so, can you set `net.ipv4.ip_unprivileged_port_start` to `0` and try again.

**Comment by zmeel** [comment]
Okay, I will look into this but I have several docker containers running that use port 80 (ie Shaarli and Vaultwarden)

**Comment by zmeel** [comment]
I have tried this:
```
docker run -d \
-e "FLATNOTES_USERNAME=<removed>" \
-e "FLATNOTES_PASSWORD=<removed>" \
-e "FLATNOTES_SECRET_KEY=<removed>" \
-v "/volume1/docker/flatnotes/data:/app/data" \
-p "49161:80" \
--sysctl "net.ipv4.ip_unprivileged_port_start=0" \
dullage/flatnotes:latest
```
I then get the following error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.ipv4.ip_unprivileged_po
rt_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown.
```

**Comment by Dullage** [comment]
> Okay, I will look into this but I have several docker containers running that use Docker port 80 (ie Shaarli and Vaultwarden) so it seems possible

I think the difference there is that those services run as root inside the container and so are able to bind to privileged ports. This is certainly the case for Vaultwarden at least. flatnotes runs as a non-privalidged user called `flatnotes` inside the container, this is good practice for security.

**Comment by Dullage** [comment]
> I have tried this:
> 
> ```
> docker run -d \
> -e "FLATNOTES_USERNAME=<removed>" \
> -e "FLATNOTES_PASSWORD=<removed>" \
> -e "FLATNOTES_SECRET_KEY=<removed>" \
> -v "/volume1/docker/flatnotes/data:/app/data" \
> -p "49161:80" \
> --sysctl "net.ipv4.ip_unprivileged_port_start=0" \
> dullage/flatnotes:latest
> ```
> 
> I then get the following error:
> 
> ```
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.ipv4.ip_unprivileged_po
> rt_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown.
> ```

It looks like there's another way to achieve the same thing. Can you please try:

```shell
docker run -d \
-e "FLATNOTES_USERNAME=<removed>" \
-e "FLATNOTES_PASSWORD=<removed>" \
-e "FLATNOTES_SECRET_KEY=<removed>" \
-v "/volume1/docker/flatnotes/data:/app/data" \
-p "49161:80" \
--cap-add NET_BIND_SERVICE \
dullage/flatnotes:latest
```

This is described [in the docker run docs](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) as:

> Bind a socket to internet domain privileged ports (port numbers less than 1024).

**Comment by zmeel** [comment]
> > I have tried this:
> > ```
> > docker run -d \
> > -e "FLATNOTES_USERNAME=<removed>" \
> > -e "FLATNOTES_PASSWORD=<removed>" \
> > -e "FLATNOTES_SECRET_KEY=<removed>" \
> > -v "/volume1/docker/flatnotes/data:/app/data" \
> > -p "49161:80" \
> > --sysctl "net.ipv4.ip_unprivileged_port_start=0" \
> > dullage/flatnotes:latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I then get the following error:
> > ```
> > docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.ipv4.ip_unprivileged_po
> > rt_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown.
> > ```
> 
> It looks like there's another way to achieve the same thing. Can you please try:
> 
> ```shell
> docker run -d \
> -e "FLATNOTES_USERNAME=<removed>" \
> -e "FLATNOTES_PASSWORD=<removed>" \
> -e "FLATNOTES_SECRET_KEY=<removed>" \
> -v "/volume1/docker/flatnotes/data:/app/data" \
> -p "49161:80" \
> --cap-add NET_BIND_SERVICE \
> dullage/flatnotes:latest
> ```
> 
> This is described [in the docker run docs](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) as:
> 
> > Bind a socket to internet domain privileged ports (port numbers less than 1024).

Tried that one 5 minutes ago. Same bind error. Also tried with flag --privileged. No luck either.

**Comment by zmeel** [comment]
`--sysctl "net.ipv4.ip_unprivileged_port_start=0"` only works with kernel version >4.4 Synology is currently running on kernel 3.10.108

**Comment by zmeel** [comment]
> Ok, I have created a test docker image that includes the option to change the bind port using an environment variable. Please can you try the image `dullage/flatnotes:28-synology-port-issue` and add an environment variable called `PORT` set to something above 1024. Then, in the port mapping, replace `80` with whatever port you chose.

![image](https://user-images.githubusercontent.com/34382336/186906180-a8c78a71-c429-4de5-8ea6-617654d8238c.png)

Yes! Now it binds to port 8080 and I can see the webpage (and login).
`2022-08-26 12:41:54 [INFO]: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)`

**Comment by Dullage** [comment]
Great news. Ok, I'll make this change in the master branch and do a new release.

Really I'd like to just change the bind port to something above 1024 but that would break all existing installations. So this is probably the best workaround until I can wrap it up with some other breaking changes.

**Comment by Dullage** [comment]
All done. v1.0.4 is now available with this additional environment variable. Glad we got to the bottom of this. Thanks for your help.
