### ISSUE TITLE
Partial words are not included in the search results

### ISSUE THREAD

**Issue by TheBestMoshe** [Dullage/flatnotes#29]
For example, if you search for *java* it will not return results with *javascript*.

**Comment by Dullage** [comment]
> For example, if you search for *java* it will not return results with *javascript*.

The flatnotes index does "stem" words E.g. `scripts` will get indexed as `script`. But for real partial word searches (like in your example) you can use wildcard expressions E.g `java*`. See [Advanced Searching](https://github.com/Dullage/flatnotes/wiki/Advanced-Searching) in the wiki.

**Comment by TheBestMoshe** [comment]
Got it. Thanks
