### ISSUE TITLE
Hide Markdown formatting

### ISSUE THREAD

**Issue by g3blv** [Dullage/flatnotes#30]
Flatnotes is something I've been looking for, and it looks great. Have you considered hiding Markdown formatting, like in this example?:

![markdown](https://user-images.githubusercontent.com/45568043/187030120-c3072d3b-c6eb-49c7-bd91-2e2cbacaffd1.gif)

**Comment by Dullage** [comment]
Thanks for the good feedback, I'm glad you like it.

Unfortunately, [the underlying editor I'm using in flatnotes](https://ui.toast.com/tui-editor) doesn't currently support this and it's not something I fancy tackling at the minute. I'll keep my eye out though as I do really like the style of the editor in your example.
