### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by TheNomad11** [Dullage/flatnotes#31]
Stupid noob question: Is there a way to change font-size? I could not find a css file, I checked in /var/lib/docker.  Thanks!

**Comment by Dullage** [comment]
Hi @TheNomad11. I wish I could just point you to a file to tweak but unfortunately, it isn't that simple. The css is created during the build process from the `.scss` files and the scss within the `.vue` files. So if you're comfortable with scss and building Docker containers then fill your boots. Other than that, all I can suggest for now is browser zoom.
