### ISSUE TITLE
2-Factor Authentication

### ISSUE THREAD

**Issue by woonaval** [Dullage/flatnotes#32]
Hi there! I just installed flatnotes using docker and everything is working perfectly, thanks a lot!
I wonder if you plan to add 2 factor authentication to the logon, as I'm a bit worried of a plain user/password logon for an internet-facing service.
Thanks for your great work!

**Comment by Dullage** [comment]
Hi @woonaval. I've no plans for 2FA at present but I completely agree with your concern. My advise would be to use a VPN or to put something like Authelia in front of flatnotes. 

I'll keep this open as a suggestion and may take a look in the future.

**Comment by Dullage** [comment]
@woonaval - This piqued my interest and wasn't too difficult to implement. As of v2.1.0 you can now optioanlly enable 2FA using a time-based one-time-password. See the [Environment Variables](https://github.com/Dullage/flatnotes/wiki/Environment-Variables) article in the wiki for more information.

**Comment by woonaval** [comment]
> 

Awesome!! In the meantime I've chosen (as you suggested) to restrict the access to flatnotes to my local network and VPN only, but this is a very welcome addition and I may rethink my setup in the future. Thank you!
