### ISSUE TITLE
Overview of Used Tags

### ISSUE THREAD

**Issue by norsemangrey** [dullage/flatnotes#35]
I just started using this and it just what I need. Great job!!

It might be useful to somewhere (perhaps related to the search area) provide a list of tags found in the notes so that the user can click on a desired tag and get a list of the notes where that tag is used.

**Comment by Dullage** [comment]
@norsemanGrey - I did start to develop this but put it on hold as I ran into a problem. As it stands, the logic I use to extract tags from a note will consider hashtags _anywhere_ in the content (including code blocks). What I found when looking at my own notes is that I really need to ignore anything in a code block as it picks up code comments e.g. `#TODO` and SQL Server temp tables e.g. `#Users`.

The API already supports retrieving a list of indexed tags (see `/api/tags`) so once I solve the codeblock issue it should be fairly simple to implement.

**Comment by DrMxrcy** [comment]
With this, Maybe a way to make collections, Similar to bookstack. The Collections could be auto generated off the tags. So if you have notes with #windows10 it will all go to a collection.

**Comment by tunip** [comment]
Additional idea: tag completion in the search field

**Comment by dullage** [comment]
A new tag menu has been added and is now available in the pre-release [v5.0.0-rc.1](https://github.com/dullage/flatnotes/releases/tag/v5.0.0-rc.1) 🎉.
