### ISSUE TITLE
Add ids to header tags to support anchoring

### ISSUE THREAD

**Issue by ShoshinNikita** [Dullage/flatnotes#41]
Hi. First, I really love the simplicity of flatnotes)

The only issue I have is an absence of `id`s for `h1`, `h2` and other header tags. It makes tables of contents almost useless because clicking on anchor links does nothing:

```markdown
# Example

- [A](#a)
	- [AA](#aa)
- [B](#b)

## A

### AA

## B
```

I believe `TOAST UI Editor` doesn't support it out of the box:

* https://github.com/nhn/tui.editor/issues/308
* https://github.com/nhn/tui.editor/issues/803
* https://github.com/nhn/tui.editor/issues/2365

The simplest solution that comes into my mind is to use `getElementsByTagName` on `Viewer` component to get all header tags and generate all ids manually.

Generation of a valid id is an another issue, but I believe it's possible to use this [code](https://github.com/yzhang-gh/vscode-markdown/blob/5f96907d93400aa3b82d826f1a0ca369916231c0/src/util/slugify.ts#L148) as a base. It is under MIT license, so, there should be no problems with copying it if the authors are mentioned.

**Comment by Dullage** [comment]
Thanks for the feedback. I agree this would be very useful and I'm sure there's something that could be done here. I'll take a look when I get a chance and let you know.

**Comment by Dullage** [comment]
I think if this was implemented I'd also look to somewhat automate the process of adding a table of contents so I'll merge this with #34.
