### ISSUE TITLE
Enhancement:  Ability to open note in WYSIWYG as default

### ISSUE THREAD

**Issue by dsfsdbvxc** [Dullage/flatnotes#48]
At the moment notes open in Markdown as default, would be nice to have a variable menu option to open in WYSIWYG

**Comment by Dullage** [comment]
It should be easy for me to get it to simply remember the last mode used. Would that suffice?

**Comment by dsfsdbvxc** [comment]
Thanks! Yea that would be useful.

**Comment by Dullage** [comment]
This is now available in v2.2.0.
