### ISSUE TITLE
Hosting Options

### ISSUE THREAD

**Issue by m3nu** [dullage/flatnotes#51]
Hi there, nice app. Kudos to everyone involved. Based on user feedback, we added Flatnotes on [PikaPods.com](https://www.pikapods.com/) for [1-click hosting](https://www.pikapods.com/pods?run=flatnotes). Will also feature it in our monthly newsletter this week.

While I love true self-hosting, it's not for everyone and every app. PikaPods is here to fill this gap and make great apps, like Flatnotes available to a wider audience. So I also wanted to check if it's an option to add a note about this managed hosting option in the README. Happy to add a PR with some initial wording.

We also offer a revenue share for app authors. Happy to discuss that too.

**Comment by Dullage** [comment]
Hey @m3nu, thank you for listing flatnotes! I've spotted PikaPods on r/selfhosted before but I've yet to take a look. It's certainly an interesting prospect and might be a way for some of my friends and family to use flatnotes without needing to self-host themselves.

When I get a chance I'll sign up for an account and try out the service.

**Comment by dullage** [comment]
Closing this issue as PikaPods has now been added as a hosted option in the README.
