### ISSUE TITLE
Buttons edit/cancel/save/delete have incorrect titles when editing note

### ISSUE THREAD

**Issue by thestahan** [Dullage/flatnotes#60]
**Description**
When editing a note, after clicking "Cancel", buttons have incorrect titles - edit has a "Cancel" title. After clicking "Cancel", which behaves like "Edit", both buttons have now "Cancel" titles. It leads to confusion and one might cancel the note instead of saving (been there).

**How to reproduce**
1. Open a note
2. Click "Edit"
3. Click "Cancel". Now the buttons should be "Cancel" and "Delete".
![image](https://user-images.githubusercontent.com/46906385/229339419-56e4d468-0d47-4523-a805-382cdc2c88df.png)
5. Click "Cancel". Both buttons should now be "Cancel".
![image](https://user-images.githubusercontent.com/46906385/229339387-aebadce3-7023-480f-9fd2-8f059035c172.png)

**Comment by Dullage** [comment]
Odd, I don't see the same behaviour. Can you please confirm:

- The browser you're using. 
- The version of flatnotes you're running.

**Comment by thestahan** [comment]
Browser: Brave v1.49.132
As per the flatnotes version, I believe it's the latest: I set up the docker container using the given docker-compose today.

It behaves the same on the demo site for me.

**Comment by thestahan** [comment]
I've double-checked and tried on incognito - the issue doesn't appear there. After disabling my extensions one by one it seems that the [TransOver](https://chrome.google.com/webstore/detail/transover/aggiiclaiamajehmlfpkjmlbadmkledi) was causing the issue. Sorry for the confusion!

**Comment by Dullage** [comment]
No worries. Glad you got to the bottom of it 👍🏻
