### ISSUE TITLE
Ability to use directories to group .md files

### ISSUE THREAD

**Issue by revilo951** [dullage/flatnotes#62]
it would be very nice to be able to use flatnotes to work on .md files that are in a simple directory structure

**Comment by Dullage** [comment]
Thanks for the suggestion, however, I'm keen to avoid adding folder support. A lot of the design ethos around flatnotes is the flat structure (hence the name).

For those that need/want a little structure there is the tagging feature.

I appreciate this is very opinionated but I'm a fan of the simplicity.

**Comment by revilo951** [comment]
I see where you're coming from. I guess my use-case is a little bit of an edge case. I'm attempting to use flatnotes as a nice UI for muggles to use for editing the markdown files in my mkdocs, which has directories.

**Comment by dullage** [comment]
Closing as duplicate of #23.
