### ISSUE TITLE
Error with new docker update v3.0.1  when upgrading

### ISSUE THREAD

**Issue by uGeek** [Dullage/flatnotes#65]
I just updated docker in Raspberry Pi (ARM64) and it doesn't start FlatNotes. I get this error:

```
exec /entrypoint.sh: no such file or directory
exec /entrypoint.sh: no such file or directory
exec /entrypoint.sh: no such file or directory
exec /entrypoint.sh: no such file or directory
exec /entrypoint.sh: no such file or directory
exec /entrypoint.sh: no such file or directory
exec /entrypoint.sh: no such file or directory
```

**Comment by Dullage** [comment]
Can you please try pulling the 3.0.1 image again i.e. `docker pull dullage/flatnotes:v3.0.1`. 

I mistakenly uploaded a bad build earlier today but replaced it soon after.

**Comment by uGeek** [comment]
Now it works!!! I have installed v3.0.1 and then the latest and everything is correct.

I have Watchtower in automated mode and it has updated just when it shouldn't.

Thank you so much. And congratulations for the service. it's amazing
