### ISSUE TITLE
Keyboard shortcut to exit note

### ISSUE THREAD

**Issue by thegreatestgiant** [dullage/flatnotes#69]
This isn't really an issue, more of a suggestion.
Whenever I want to cancel a note, or save and exit, I like to press esc

Also you should make a feature suggestion forums site or area (if there already is can you please direct me there?)

**Comment by dullage** [comment]
Thanks for the suggestion. This is very similar to #59 but you additionally mention cancelling. How would you propose to choose between cancelling and saving & exiting? If it were a modal-based question, would that not negate the benefit of the keyboard shortcut?

**Comment by dullage** [comment]
As of [5.2.0](https://github.com/dullage/flatnotes/releases/tag/v5.2.0) you can now exit edit mode with the escape key. 🚀
