### ISSUE TITLE
Provide stable linking between notes and/or backlinks

### ISSUE THREAD

**Issue by philipp-koch** [dullage/flatnotes#75]
It would be useful to be able to **link to another note in a "stable" way**: Currently, one could link to the note via its web address, but those links will break if the note's filename changes. Having a mechanism for internal links (be it that Flatnotes either would track filename changes and apply those changes to existing links, or it would have some kind of internal ID mechanism so that notes can be referenced independent of their filename / URI).

Furthermore, it would be extremely beneficial to see "what links here" when viewing a note (i.e. a list of backlinks from other notes that link to the current note).

**Comment by dullage** [comment]
Thanks for the suggestion 👍.

This is similar to #14 which is the most popular suggestion for flatnotes and _is_ something I'd like to do. My only concern is tracking renames. This is possible if renamed through flatnotes but not if renamed outside of flatnotes (something I'd like to continue to support). I could, as you say, use an internal ID mechanism but this would move flatnotes further away from the simple file-based design it has now.

**Comment by philipp-koch** [comment]
One solution could be to hash the markdown files with SHA-256 or similar, so that as long as only their filename has changed (but their content has been untouched), these kinds of changes could be identified. But I agree this wouldn't work if both filename and content have been altered; in this situation, Benotes could show a file selection dialog asking to point to the file / note meant by an existing link to a now-unknown file (e.g. "Note XY links to note AB (filename AB); this seems to have been either deleted or changed outside Benotes. Please select the note this link refers to"). Or, alternatively, you could let the user simply search the existing notes to point to the correct one. Or, more sophisticated, you could not only hash a note every time it is saved and keep that hash in a database as well, but also build some kind of "statistical / linguistic profile" of the note (like a list of the 50 most used words, sorted by their number of occurrences in a given note; number of paragraphs; median sentence length; words total; ...), so that it could be heuristically determined which group of, let's say, three notes of all the existing ones most likely contains the (changed) note that originally has been linked to. 

Anyway, in the end, it's obviously just not very practical to allow changing your data sources externally while keeping references intact - but I understand that this is a design principle you find important, and you have every right to. :-)

**Comment by dullage** [comment]
Thanks for the suggestions. I've been thinking about this some more and in the spirit of keeping things simple, I'm tempted to simply not handle renames at all. Personally speaking, I hardly ever rename a note and I can imagine this is the case for a lot of other people as well.

As you suggest, what I could do is simply update the "Note not found" message with a quick link to perform a search using the not-found note name as the search term. This should suffice for a large percentage of cases without adding any complexity.

**Comment by philipp-koch** [comment]
I completely agree with you - it's reasonable to expect a user to correct broken links, because if one ever feels the urge to rename a note, I suspect that would be in the software it is normally being edited anyway (i.e. flatnotes). And if the person chooses to use several apps on the same files, they need to take side effects of their actions into account (for all apps involved).
