### ISSUE TITLE
Allow Hyphens in Tags

### ISSUE THREAD

**Issue by philipp-koch** [dullage/flatnotes#77]
Currently, underscores are the only allowed separator chars for tags, and hyphens are not allowed and thus prevent a hashtag to be recognized as such. For instance, `#hello_world` is recognized, can be searched for etc., while `#hello-world` doesn't work. Obsidian (which I've used for my markdown files) supports tags with hyphens, so my files have quite a bunch of hyphenated hashtags, and I guess, those of other users might as well.

**Comment by dullage** [comment]
I'm not opposed to adding hyphens but it would require a change to the index which would mean a re-index of all notes upon update. So I'll leave this open as a suggestion and if it gets more votes, or I have to do another change to the index anyway, then I should be able to get this implemented.

**Comment by romu70** [comment]
I’m not even aware of this tagging feature. How does it work? Thanks.

**Comment by dullage** [comment]
Take a look at the related [wiki article](https://github.com/dullage/flatnotes/wiki/Tagging). It should hopefully give you a good overview.

**Comment by romu70** [comment]
Thanks. Just tested. Is there something I do wrong?

<img width="530" alt="image" src="https://github.com/dullage/flatnotes/assets/1898319/4679cd8a-27aa-45b7-8d06-3c9f349f1e3d">

**Comment by dullage** [comment]
I've just re-read the wiki page and realised that whilst it explains _how_ to tag a note, it doesn't explain what it does. I've added this section:

> Tags are indexed separately from the rest of the content and so can be searched separately either by using the field prefix e.g. "tags:work" or using the hashtag shortcut e.g. "#work".

**Comment by romu70** [comment]
Got it, thanks. It would be nice to :
- Display tags as…tags in the notes
- Displays tags in the notes list by default. We can imagine show them at the left of the timestamp. So everything will stay on the same line, as it is today.

**Comment by dullage** [comment]
Thanks to @ChristianAvila, hyphens are now supported in the `:develop` image and will be generally available in the next release.
