### ISSUE TITLE
Code block should use monospace font

### ISSUE THREAD

**Issue by kyoheiu** [dullage/flatnotes#78]
Idk if this is due to my web browser setting, but I can't see code blocks with monospace.
(FYI, e.g. code blocks in GitHub's README come with monospace)

Example:
![MSRV-flatnotes](https://github.com/dullage/flatnotes/assets/61998590/c766ef97-57f5-47db-88e8-80813b8cafa7)

It'd be better to use monospace in such blocks.

**Comment by dullage** [comment]
I left the font for the code blocks as styled by the Toast UI Editor. 

```css
font-family: Consolas,Courier,Apple SD 산돌고딕 Neo,-apple-system,Lucida Grande,Apple SD Gothic Neo,맑은 고딕,Malgun Gothic,Segoe UI,돋움,dotum,sans-serif;
```

The first 2 (`Consolas` and `Courier`) are monospaced but many of the fallbacks are not. Presumably, you don't have `Consolas` or `Courier` available and so are ending up with one of the others. I'll update the font-family in an upcoming release which should solve this.
