### ISSUE TITLE
Why images now shown?

### ISSUE THREAD

**Issue by HerrAugust** [dullage/flatnotes#86]
Hello,

I use to have images linked in my md files as: `![ALT text](media_xxx/image.jpg)` and the file structure is:

```
.
|- file.md
|- media_xxx/
|------ image.jpg
```

Is there any way to get it shown? Maybe I need some more routing or the path is wrong?

Thank you!

**Comment by dullage** [comment]
Unfortunately flatnotes doesn't currently support serving images in this way. You can either use an external URL or use the toolbar option to embed the image in the markdown file itself.

**Comment by HerrAugust** [comment]
Thank you for the reply!

Before I edit the file and try my things, would it work to edit main.py and say:

```
@app.get('media_{something}', ....)
async def get_media():
   ...
```

**Comment by dullage** [comment]
Something like this _might_ work but there's a lot to consider. More than I can do without really opening up a project I'm afraid.

You might even be able to do something with a reverse proxy without needing to touch the app. Might be worth considering this option as well.
