### ISSUE TITLE
Documentation for FLATNOTES_PATH when using Docker is wrong

### ISSUE THREAD

**Issue by codemicro** [dullage/flatnotes#89]
Hey!

[This page](https://github.com/Dullage/flatnotes/wiki/Environment-Variables#flatnotes_path) says that the default value for `FLATNOTES_PATH` when running in Docker is `/app/data`, but the `Dockerfile` says `/data`.

https://github.com/dullage/flatnotes/blob/ea6751464f878151b8b7abfad7247539bf3d5e44/Dockerfile#L28

Cheers :)

**Comment by dullage** [comment]
Thanks for the heads up. I must have missed this wiki page when the container path was changed. It's sorted now.
