### ISSUE TITLE
Any commission from PikaPods installs?

### ISSUE THREAD

**Issue by raelb** [dullage/flatnotes#91]
Hi,
I'm curious, as the author of this project, do you get any commission from PikaPods installs? :)

**Comment by dullage** [comment]
Hey @raelb 👋

They do have a revenue sharing model but as far as I know, flatnotes isn't currently part of that scheme.

Why do you ask?

**Comment by raelb** [comment]
Just curious. I was thinking if i made an open source app, would I be able to monetize on that platform :)
