### ISSUE TITLE
401 when behind a Proxy (NPM)

### ISSUE THREAD

**Issue by hctrr** [dullage/flatnotes#93]
Deployment method: container
auth: none

when leveraging a Proxy such as NPM, it generates constant 401 errors:
![image](https://github.com/dullage/flatnotes/assets/15852711/ac247d45-7058-4554-b775-43fd3209e90c)

However, when navigating directly to the flatnote instance (IP:Port) this is not applicable.

**Comment by dullage** [comment]
I'm not sure I can do much to help here. If it's fine without a proxy involved but doesn't work with the proxy then it must be something to do with the proxy setup. 

I have mine running behind nginx as a reverse proxy and it works fine. 

The only thing I can suggest is to check that headers are being forwarded properly. Even with authentication disabled, the client still sends a blank authorisation header.

**Comment by hctrr** [comment]
@dullage - for your instance, do you have any custom nginx configuration set?

**Comment by dullage** [comment]
Nothing special, no. Just a straight forward reverse proxy setup.

**Comment by hctrr** [comment]
I'll be closing this issue as I just tested with Cloudflare and all works as expected. 
I'll have to look into my NPM instance to see why its performing like this, but clearly the challenge is over on NPM.

thank you, @dullage, for your time.
