### ISSUE TITLE
Dark text with dark bg

### ISSUE THREAD

**Issue by mathyvds** [dullage/flatnotes#94]
In dark mode:
The text is black with grey background, so almost unreadable when making a list in a cell (table)

**Comment by dullage** [comment]
Hi @mathyvds 👋 

I'm not sure where you're referring to. This is what a dark mode table looks like to me:

![image](https://github.com/dullage/flatnotes/assets/16575268/d59e96de-c605-445a-bd61-3bea0b47d8ae)

Can you please upload a screenshot and also confirm the version of flatnotes you are running and the browser you are using.

**Comment by mathyvds** [comment]
Hi @dullage 

Ofcourse!
![image](https://github.com/dullage/flatnotes/assets/6977613/7d63c7d4-d0c5-4086-8715-a20990917297)

This occurs when using the list feature.
Using WYSIWYG-editor, v3.1.1 on Chrome.

**Comment by dullage** [comment]
Gotcha 👍. Ok, I'll get it sorted in the next release.
