### ISSUE TITLE
[Feature Request] Can it scan .md in subfolder of /data

### ISSUE THREAD

**Issue by xh542428798** [dullage/flatnotes#95]
could It be able to read/organize content hierarchically based on the folder structure the files in /data folder?

**Comment by dullage** [comment]
Thanks for the suggestion, however, I'm keen to avoid adding folder support. A lot of the design ethos around flatnotes is the flat structure (hence the name).

For those that need/want a little structure there is the tagging feature.

I appreciate this is very opinionated but I'm a fan of the simplicity.
