### ISSUE TITLE
port mapping doesnt seem to work

### ISSUE THREAD

**Issue by david-corkill** [dullage/flatnotes#96]
Port mapping doesn't seem to work for me, it is always 8080 no matter what i change the value to

**Comment by david-corkill** [comment]
ignore me, this looks like it is because I use macvlan

**Comment by lokesh-krishna** [comment]
I'm facing the same issue, with `docker compose up` giving the following message:

```
flatnotes    | INFO:        Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

despite my `docker-compose.yml` specifying 8070 as the port.

**Comment by dullage** [comment]
> I'm facing the same issue, with `docker compose up` giving the following message:
> 
> 
> 
> ```
> 
> flatnotes    | INFO:        Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
> 
> ```
> 
> 
> 
> despite my `docker-compose.yml` specifying 8070 as the port. 

Can you share your docker compose file please and I'll try and help. Don't forget to obfuscate any secrets.

**Comment by lokesh-krishna** [comment]
That did it! Thank you so, so much!
