### ISSUE TITLE
Good links to integrate any features

### ISSUE THREAD

**Issue by passionate2023** [dullage/flatnotes#98]
Good links for web projects

https://codepen.io/saadeghi/pen/OJypbNM
https://codepen.io/DylanMacnab/pen/ZdvxQd
https://codepen.io/pirrera/pen/bqVeGx
https://codepen.io/salixdubois/pen/oZyMYG
https://codepen.io/JavaScriptJunkie/pen/pPRooV
https://codepen.io/mmousawy/pen/mOVByO
https://codepen.io/atner/pen/kMdVBy
https://codepen.io/Jhonierpc/pen/MWgBJpy
https://codepen.io/sarath-ar/pen/dMKxxM
https://codepen.io/foxeisen/pen/bqZxLa
https://codepen.io/markmead/pen/xJxyGO
https://codepen.io/Sonick/pen/AwXJdM
https://codepen.io/AlexWarnes/pen/jXYYKL
https://codepen.io/omaf/full/NgWzmL
https://codepen.io/EvilSpark/pen/GVJZdj
https://codepen.io/codingandstuff/pen/rNNNzyW

**Comment by dullage** [comment]
Without context, I'm unsure of the use of these links.

**Comment by passionate2023** [comment]
Context is to have beautiful buttons or some good themes and features with icons for the flatnotes....Working code with examples would help to add them to the project if possible or can be added.
